# -*- coding: utf-8 -*-
"""grade_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cLLsXgry825IrJ-mVex14TbXaX9BJbN8
"""

# Day 2: Input System

student_name = input("Enter student name: ")
marks = int(input("Enter marks: "))

print("Student Name:", student_name)
print("Marks:", marks)

# Day 3: Input + Grading Logic

student_name = input("Enter student name: ")
marks = int(input("Enter marks: "))

if marks >= 90:
    grade = "A"
    message = "Excellent work!"
elif marks >= 80:
    grade = "B"
    message = "Very Good! Keep it up!"
elif marks >= 70:
    grade = "C"
    message = "Good effort!"
elif marks >= 60:
    grade = "D"
    message = "Keep practicing!"
else:
    grade = "F"
    message = "Don't give up!"

print("\nRESULT")
print("Name:", student_name)
print("Marks:", marks)
print("Grade:", grade)
print("Message:", message)

# Day 4: Validation Using Loop

student_name = input("Enter student name: ")

while True:
    try:
        marks = int(input("Enter marks (0-100): "))
        if 0 <= marks <= 100:
            break
        else:
            print("Marks must be between 0 and 100.")
    except ValueError:
        print("Enter numbers only.")

if marks >= 90:
    grade = "A"
elif marks >= 80:
    grade = "B"
elif marks >= 70:
    grade = "C"
elif marks >= 60:
    grade = "D"
else:
    grade = "F"

print("\nRESULT")
print("Name:", student_name)
print("Marks:", marks)
print("Grade:", grade)

# Day 5: Final Student Grade Calculator

def get_valid_marks():
    while True:
        try:
            marks = int(input("Enter marks (0-100): "))
            if 0 <= marks <= 100:
                return marks
            else:
                print("Marks must be between 0 and 100.")
        except ValueError:
            print("Enter valid numbers only.")


def calculate_grade(marks):
    if marks >= 90:
        return "A", "Excellent work!"
    elif marks >= 80:
        return "B", "Very Good! Keep it up!"
    elif marks >= 70:
        return "C", "Good effort!"
    elif marks >= 60:
        return "D", "Keep practicing!"
    else:
        return "F", "Don't give up!"


# Main Program
student_name = input("Enter student name: ")
marks = get_valid_marks()
grade, message = calculate_grade(marks)

print("\nRESULT")
print("Name:", student_name)
print("Marks:", marks)
print("Grade:", grade)
print("Message:", message)