# -*- coding: utf-8 -*-
"""Personal_intro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GEskypuyxC4cVrnXxwIV3wtkx8_xRnMc
"""

# Day 1 - Hello World Program
print("Hello, World!")

# Day 2 - User Input

name = input("Enter your name: ")
age = input("Enter your age: ")

print(name)
print(age)

# Day 3 - Personalized Welcome Message

name = input("Enter your name: ")
age = input("Enter your age: ")

print(f"Welcome {name}!")
print(f"You are {age} years old.")

# Day 4 - Enhanced Program

name = input("What is your name? ")
age = input("How old are you? ")
city = input("Which city do you live in? ")
hobby = input("What is your favorite hobby? ")

print("\n----------------------------")
print(f"Hello {name}!")
print(f"Age: {age}")
print(f"City: {city}")
print(f"Hobby: {hobby}")
print("----------------------------")

# Personal Introduction Program
# Week 1 Internship Task
# Day 5 - Final Version

# Taking user input
name = input("What is your name? ")
age = input("How old are you? ")
city = input("Which city do you live in? ")
hobby = input("What is your favorite hobby? ")

# Displaying welcome message
print("\n Welcome", name, "! ")
print(f"You are {age} years old.")
print(f"You live in {city}.")
print(f"You love {hobby}. ")

